# Generated by Django 3.2 on 2021-04-26 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=20)),
                ('patient_name', models.CharField(max_length=20)),
                ('img_type', models.CharField(max_length=20)),
                ('photo', models.ImageField(upload_to='')),
                ('pred_result', models.CharField(max_length=100)),
                ('note', models.CharField(max_length=100, null=True)),
                ('pred_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pred.user')),
            ],
        ),
    ]
